"""Stat roll ranges for Unique/Set items.

Data comes from repository/ranges.json (generated by tools/gen_ranges.py from
the d2data game-data dump). For a parsed item we return its full stat list
with min/max ranges and, where the OCR'd affix matches, the actual roll.
"""
import json
import re

from d2rlootreader.cfg import REPOSITORY_DIR

_data = None


def _load():
    global _data
    if _data is None:
        try:
            with open(REPOSITORY_DIR / "ranges.json", encoding="utf-8") as f:
                _data = json.load(f)
        except (FileNotFoundError, json.JSONDecodeError):
            _data = {}
    return _data


def _render(tmpl, params):
    out = tmpl
    for p in params or []:
        token = "#" if isinstance(p, (int, float)) else "["
        i = out.find(token)
        if i < 0:
            continue
        if token == "#":
            out = out[:i] + str(p) + out[i + 1:]
        else:
            j = out.find("]", i)
            out = out[:i] + str(p) + out[j + 1:] if j >= 0 else out
    return out


def magic_affix_ranges(item):
    """Tier-annotated stat list for Magic/Rare/Crafted/superior-Base items.

    Each rolled affix is matched to its prefix/suffix tier: which tier the
    value belongs to, that tier's min-max and the overall cap for the stat.
    Values outside every known tier are flagged (usually an OCR misread).
    """
    quality = (item or {}).get("quality")
    if quality not in ("Magic", "Rare", "Crafted", "Base"):
        return None
    tiers_db = _load().get("affix_tiers", {})
    props = []
    for tmpl, params in item.get("affixes") or []:
        rendered = _render(tmpl, params)
        val = params[0] if params and isinstance(params[0], int) else None
        cand = tiers_db.get(tmpl) if tmpl.count("#") == 1 else None
        if not cand or val in (None, 0):
            props.append({"label": rendered, "tmpl": None, "min": 0, "max": 0, "var": False})
            continue
        # White items only roll the "Superior" tier; magic+ never do.
        if quality == "Base":
            cand = [t for t in cand if t["name"] == "Superior"]
        else:
            cand = [t for t in cand if t["name"] != "Superior"]
        if not cand:
            props.append({"label": rendered, "tmpl": None, "min": 0, "max": 0, "var": False})
            continue
        overall = max(t["max"] for t in cand)
        matches = [t for t in cand if t["min"] <= val <= t["max"]]
        if matches:
            best = min(matches, key=lambda t: t["max"] - t["min"])
            p = {"label": f"{rendered}  ['{best['name']}' {best['min']}-{best['max']}, cap {overall}]",
                 "tmpl": None, "min": best["min"], "max": best["max"], "var": True}
            if val >= overall:
                p.update(roll=val, perfect=True)
            props.append(p)
        else:
            props.append({"label": f"{rendered}  [no tier matches, stat cap {overall}]",
                          "tmpl": None, "min": 0, "max": overall, "var": True,
                          "roll": val, "offrange": True})
    return props or None


def get_item_ranges(item):
    """Return a list of prop dicts for a Unique/Set item, or None.

    Each prop: {label, min, max, var, tmpl} plus:
      roll      — the value OCR'd from this item's tooltip (variable props only)
      perfect   — True when roll == max
      offrange  — True when the roll is outside [min, max] (OCR misread or
                  data drift; worth checking by eye)
    """
    quality = (item or {}).get("quality")
    name = (item or {}).get("name")
    if quality not in ("Unique", "Set", "Runeword") or not name:
        return None

    bucket = _load().get(quality.lower(), {})
    entry = bucket.get(name)
    if entry is None:
        low = name.lower()
        entry = next((v for k, v in bucket.items() if k.lower() == low), None)
    if entry is None:
        return None

    props = [dict(p) for p in entry.get("props", [])]
    affixes = item.get("affixes") or []
    tooltip = item.get("tooltip") or []
    for p in props:
        tmpl = p.get("tmpl")
        if not (tmpl and p.get("var")):
            continue
        for a in affixes:
            if a[0] == tmpl and a[1]:
                val = a[1][0]
                if isinstance(val, (int, float)):
                    p["roll"] = val
                    p["perfect"] = val >= p["max"]
                    p["offrange"] = not (p["min"] <= val <= p["max"])
                break
        if "roll" not in p:
            # the stat line existed but failed template matching (OCR noise)
            # — recover the roll from the raw tooltip text by keywords
            val = _roll_from_tooltip(tooltip, tmpl, p["max"])
            if val is not None:
                p["roll"] = val
                p["perfect"] = val >= p["max"]
                p["offrange"] = not (p["min"] <= val <= p["max"])
    return props


def _roll_from_tooltip(tooltip, tmpl, cap):
    """Find the tooltip line carrying the template's words and take its
    number as the roll. Word matching is fuzzy (a word counts when its
    first 4 letters appear — OCR loves "Items"→"Iteme"); the best line
    needs 75% of the words. Only accepted when plausible vs the cap."""
    words = [w.lower() for w in re.findall(r"[A-Za-z]{3,}", tmpl)]
    if not words:
        return None
    best_val, best_score = None, 0.0
    for ln in tooltip:
        low = ln.lower()
        hit = sum(1 for w in words if w in low or w[:4] in low)
        score = hit / len(words)
        if score < 0.75 or score < best_score:
            continue
        nums = re.findall(r"\d+", ln)
        if not nums:
            continue
        val = int(nums[0])
        if 0 < val <= max(cap * 2, cap + 20):
            if score > best_score:
                best_score, best_val = score, val
    return best_val
